      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@52.45.7.233 << 'EOF'
            cd /home/ubuntu/project-folder
            git pull origin main
            npm install --production
            npm run build
            sudo rm -rf /var/www/html/*  # Clear old build files
            sudo cp -r build/* /var/www/html/  # Copy new build files
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo systemctl restart nginx
            pm2 restart all
          EOF

